# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ends', to='transport.City'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='transport.City'),
        ),
    ]
