# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20180306_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
