# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20180308_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='max_weight',
            field=models.IntegerField(default=5),
        ),
    ]
