# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_trip_max_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Parcel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Trip')),
            ],
        ),
    ]
