# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20180408_0849'),
        ('transport', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='meeting_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_from', to='transport.Location'),
        ),
        migrations.AddField(
            model_name='offer',
            name='meeting_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_to', to='transport.Location'),
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='globals.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
