# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Avatar'),
        ),
    ]
