# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20180306_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rider_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sender_rating',
            field=models.IntegerField(default=0),
        ),
    ]
