# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20180408_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_id', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GooglePlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_id', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vkontakte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_id', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
