# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_yandex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odnoklassniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_id', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
